// User Types
const USER_TYPES = {
  USER: 'USER',
  VENDOR: 'VENDOR',
  ADMIN: 'ADMIN'
};

// Order Status
const ORDER_STATUS = {
  ORDER_RECEIVED: 'ORDER_RECEIVED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  IN_PREPARATION: 'IN_PREPARATION',
  IN_SHIPPING: 'IN_SHIPPING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  AWAITING_RESPONSE: 'AWAITING_RESPONSE'
};

// Product Status
const PRODUCT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  SOLD_OUT: 'SOLD_OUT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  REJECTED: 'REJECTED'
};

// Vendor Status
const VENDOR_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED'
};

// Payment Method
const PAYMENT_METHOD = {
  BANK_CARD: 'BANK_CARD',
  BANK_TRANSFER: 'BANK_TRANSFER'
};

// Payment Status
const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  VERIFIED: 'VERIFIED'
};

// Cart Status
const CART_STATUS = {
  ACTIVE: 'ACTIVE',
  SAVED: 'SAVED',
  ABANDONED: 'ABANDONED',
  CONVERTED: 'CONVERTED',
  EXPIRED: 'EXPIRED'
};

// Wishlist Privacy
const WISHLIST_PRIVACY = {
  PRIVATE: 'PRIVATE',
  PUBLIC: 'PUBLIC',
  COLLABORATIVE: 'COLLABORATIVE'
};

// Negotiation Status
const NEGOTIATION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED'
};

// Review Status
const REVIEW_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  HIDDEN: 'HIDDEN'
};

// Support Ticket Status
const TICKET_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

// Support Ticket Priority
const TICKET_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH'
};

// Offer Status
const OFFER_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SCHEDULED: 'SCHEDULED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED'
};

// Offer Type
const OFFER_TYPE = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED_AMOUNT: 'FIXED_AMOUNT',
  BUY_X_GET_Y: 'BUY_X_GET_Y',
  BUNDLE: 'BUNDLE',
  FLASH_SALE: 'FLASH_SALE'
};

// Coupon Type
const COUPON_TYPE = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED_AMOUNT: 'FIXED_AMOUNT',
  FREE_SHIPPING: 'FREE_SHIPPING',
  BOGO: 'BOGO'
};

// Point Transaction Type
const POINT_TRANSACTION_TYPE = {
  EARNED: 'EARNED',
  REDEEMED: 'REDEEMED',
  EXPIRED: 'EXPIRED',
  ADJUSTED: 'ADJUSTED',
  REFERRAL: 'REFERRAL',
  REVIEW: 'REVIEW',
  PURCHASE: 'PURCHASE'
};

// Wallet Transaction Type
const WALLET_TRANSACTION_TYPE = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT',
  COMMISSION: 'COMMISSION',
  REFUND: 'REFUND',
  PAYOUT: 'PAYOUT',
  TRANSFER: 'TRANSFER',
  FREEZE: 'FREEZE',
  UNFREEZE: 'UNFREEZE'
};

// Shipping Method
const SHIPPING_METHOD = {
  SITE_INTERMEDIARIES: 'SITE_INTERMEDIARIES',
  CUSTOM_AGENT: 'CUSTOM_AGENT'
};

module.exports = {
  USER_TYPES,
  ORDER_STATUS,
  PRODUCT_STATUS,
  VENDOR_STATUS,
  PAYMENT_METHOD,
  PAYMENT_STATUS,
  CART_STATUS,
  WISHLIST_PRIVACY,
  NEGOTIATION_STATUS,
  REVIEW_STATUS,
  TICKET_STATUS,
  TICKET_PRIORITY,
  OFFER_STATUS,
  OFFER_TYPE,
  COUPON_TYPE,
  POINT_TRANSACTION_TYPE,
  WALLET_TRANSACTION_TYPE,
  SHIPPING_METHOD
};



